# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

#  Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [3]:
import numpy as np

list1 = list(map(int,input("Enter 5 elements for list 1 with space ").split()))
list2 = list(map(int,input("Enter 5 elements for list 1 with space ").split()))
print()
arr1 = np.array(list1)
arr2 = np.array(list2)

print(" List1:",list1,"\n","List2:",list2)
print("\nNumpy,\n\t Array1:",arr1,"\n\t","Array2:",arr2)
print()
arr12= np.concatenate((arr1, arr2), axis=None)
print("The concatenated array is:",arr12)

arr12.sort()
print("Sorted concatenated array is:",arr12)

Enter 5 elements for list 1 with space 1 2 3 4 7
Enter 5 elements for list 1 with space 5 6 7 9 5

 List1: [1, 2, 3, 4, 7] 
 List2: [5, 6, 7, 9, 5]

Numpy,
	 Array1: [1 2 3 4 7] 
	 Array2: [5 6 7 9 5]

The concatenated array is: [1 2 3 4 7 5 6 7 9 5]
Sorted concatenated array is: [1 2 3 4 5 5 6 7 7 9]


#  Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [4]:
import numpy as np

# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )

print("Array is of type: ", type(arr))

print("No. of dimensions: ", arr.ndim)

print("Shape of array: ", arr.shape)

print("Size of array: ", arr.size)

print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


#  Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2, 5))
# Modify the 2D numpy array (View object)
arr_2d[0][0] = 22
print('1D Numpy array:')
print(arr)
print('2D Numpy array:')
print(arr_2d)

1D Numpy array:
[22  1  2  3  4  5  6  7  8  9]
2D Numpy array:
[[22  1  2  3  4]
 [ 5  6  7  8  9]]


In [6]:
import numpy as np
def main():
    print('*** Convert a 1D array to a 2D Numpy array ***')
    # create 1D numpy array from a list
    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    print('1D Numpy array:')
    print(arr)
    # Convert 1D array to a 2D numpy array of 2 rows and 3 columns
    arr_2d = np.reshape(arr, (2, 5))
    print('2D Numpy array:')
    print(arr_2d)
    print('Shape of 2D array must be compatible to 1D array')
    # Converting 1D array to a 2D numpy array of incompatible shape will cause error
    #arr_2d = np.reshape(arr, (2, 3))
    #ValueError: cannot reshape array of size 10 into shape (2,3)
    print('Reshaped 2D array is a view of 1D array')
    # Modify the 2D numpy array (View object)
    arr_2d[0][0] = 22
    print('1D Numpy array:')
    print(arr)
    print('2D Numpy array:')
    print(arr_2d)
    print('Convert a 1D Numpy array to a 3D Numpy array using numpy.reshape()')
    arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
    print('1D Numpy array:')
    print(arr)
    # Convert 1D Numpy array to a 3D array with 2 matrices of shape 2X3
    arr_3d = np.reshape(arr, (2, 2, 3))
    print('3D Numpy array:')
    print(arr_3d)
    print('*** Convert 1D Numpy array to 2D numpy array along the column ***')
    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    print('1D Numpy array:')
    print(arr)
    # column wise conversion of 1D numpy array to 2D Numpy array
    arr_2d = np.reshape(arr, (2, 5), order='F')
    print('2D Numpy array:')
    print(arr_2d)
    print('*** Convert 2D aray to 1D array as copy ***')
    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    print('1D Numpy array:')
    print(arr)
    arr_2d = np.reshape(arr, (2, 5)).copy()
    print('2D Numpy array:')
    print(arr_2d)
    # Modify the 2D numpy array and it will not affect original 1D array
    arr_2d[0][0] = 22
    print('1D Numpy array:')
    print(arr)
    print('2D Numpy array:')
    print(arr_2d)
if __name__ == '__main__':
    main()

*** Convert a 1D array to a 2D Numpy array ***
1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]
2D Numpy array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
Shape of 2D array must be compatible to 1D array
Reshaped 2D array is a view of 1D array
1D Numpy array:
[22  1  2  3  4  5  6  7  8  9]
2D Numpy array:
[[22  1  2  3  4]
 [ 5  6  7  8  9]]
Convert a 1D Numpy array to a 3D Numpy array using numpy.reshape()
1D Numpy array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
3D Numpy array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
*** Convert 1D Numpy array to 2D numpy array along the column ***
1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]
2D Numpy array:
[[0 2 4 6 8]
 [1 3 5 7 9]]
*** Convert 2D aray to 1D array as copy ***
1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]
2D Numpy array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]
2D Numpy array:
[[22  1  2  3  4]
 [ 5  6  7  8  9]]


#  Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [7]:
import numpy as np
  
# input array 
arr1 = np.array([ 1, 2, 3] ) 
print ("1st Input array : \n", arr1)  
  
arr2 = np.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", arr2)  
  
# Stacking the two arrays vertically 
arrv = np.vstack((arr1, arr2)) 
print ("Output vertically stacked array:\n ", arrv) 

# Stacking the two arrays horizontally 
arrh = np.hstack((arr1, arr2)) 
print ("Output vertically stacked array:\n ", arrh) 


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output vertically stacked array:
  [[1 2 3]
 [4 5 6]]
Output vertically stacked array:
  [1 2 3 4 5 6]


#  Questions 6:
How to get unique items and counts of unique items?

In [8]:
# Python program to check to get unique item and its count  
# to get unique values from list 
# using traversal  
  
# function to get unique values 
def unique(list1): 
  
    # intilize a null list 
    u_list = [] 
      
    # traverse for all elements 
    for x in list1: 
        # check if exists in unique_list or not 
        if x not in u_list: 
            u_list.append(x) 
    # print list 
    for x in u_list: 
        print (x), 
      
    
list1 = [10, 20, 10, 30, 40, 40] 
print("the unique values from 1st list is") 
unique(list1) 
  
  
list2 =[1, 2, 1, 1, 3, 4, 3, 3, 5] 
print("\nthe unique values from 2nd list is") 
unique(list2)
print()
new_set = set(list1) 
print("No of unique items in the list1 are:", len(new_set))
new_set = set(list2) 
print("No of unique items in the list2 are:", len(new_set))


the unique values from 1st list is
10
20
30
40

the unique values from 2nd list is
1
2
3
4
5

No of unique items in the list1 are: 4
No of unique items in the list2 are: 5
